### ISSUE TITLE
lang not working other than 'en'

### ISSUE THREAD

**Issue by mytc** [douglasmiranda/django-wysiwyg-redactor#101]
I tried to use language other than english such as chinese and italian, but when define lang with `zh_cn` or `it`..etc, it is not working. 
The console show this error:
redactor.js:5701 Uncaught TypeError: Cannot read property 'html' of undefined

Is it a bug or just a configuration error?

**Comment by shapoglyk** [comment]
I have same problem. Only with 'lang': 'en' option redactor is working.
