### ISSUE TITLE
Redactor Options that are boolean have no effect

### ISSUE THREAD

**Issue by meetbryce** [douglasmiranda/django-wysiwyg-redactor#104]
Redactor Options set both at the global and model field level work just fine unless they're boolean.

Specifically we vitally need to set:
`replaceDivs: false, paragraphize: false`

We attempted to set this using:
`redactor_options={'placeholder': 'Step-by-step guide goes here...', 'replaceDivs': 'false', 'paragraphize': 'false' }`

**Comment by bilabon** [comment]
@meetbryce Thanks. You've saved me a lot of time! It works for me: `REDACTOR_OPTIONS = {'lang': 'en', 'replaceDivs': False, }`

**Comment by meetbryce** [comment]
Glad I could help!


On Thu, Dec 17, 2015 at 9:54 AM Dmytro Bazas <notifications@github.com> wrote:
@meetbryce Thanks. You've saved me a lot of time! It works for me: REDACTOR_OPTIONS = {'lang': 'en', 'replaceDivs': False, }

**Comment by swdelaney2** [comment]
Oddly, I can get

    'focus': 'true'

to work just fine, but I cannot get script or structure to work, whether I use 'true' or True.

**Comment by douglasmiranda** [comment]
Fixed! #105 :D
