### ISSUE TITLE
The textedit is rendered many times in the page

### ISSUE THREAD

**Issue by karimone** [douglasmiranda/django-wysiwyg-redactor#112]
I have an issue. All my redactor fields are rendered 3 times then I get a textfield "redactored" and then two copies above. I tried to remove all JS except the {{ form.media }} but I always get the same error. Do you have any idea?

![voila_2015-11-15_21 17 57](https://cloud.githubusercontent.com/assets/564180/11170475/5a5eb4a0-8bde-11e5-9362-08377fb49ebf.png)

**Comment by karimone** [comment]
I downgraded to the version 0.4.5 and seems to help. My settings are quite simple:
```
REDACTOR_OPTIONS = {
    'lang': 'en',
    'buttons': [
        'formatting', 'bold', 'italic', 'deleted', 'unorderedlist', 'orderedlist',
        'outdent', 'indent', 'alignment', 'horizontalrule', 'html'
    ],
    'deniedTags': [],
    'paragraphize': False,
```

**Comment by karimone** [comment]
I still have the same problem in some bootstrap modals :-(

**Comment by shapoglyk** [comment]
Django==1.9
django-wysiwyg-redactor==0.4.9
Same problem. I am using this trick to hide them.
```javascript
var redactor_box = $('.redactor-box');
            $.each(redactor_box, function(){
                $(this).children('.redactor-box').hide();
            });
```

**Comment by karimone** [comment]
Works using the 0.4.5?

**Comment by shapoglyk** [comment]
@karimone, tried to test it, but got import errors, so I don't know.

**Comment by douglasmiranda** [comment]
Can't replicate the issue.

Are you using outside the Django Admin?

**Comment by karimone** [comment]
Yes, I'll take a look with the last version again, but could be a problem on my website.

**Comment by douglasmiranda** [comment]
Please try the latest version: 0.4.9.1
