### ISSUE TITLE
Update Admin Widget Override

### ISSUE THREAD

**Issue by fission6** [douglasmiranda/django-wysiwyg-redactor#116]
For recent Django versions, the django redactor docs and Readme should offer the following approach:

https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides

```
from django import forms
from redactor.widgets import RedactorEditor
from blog.models import Entry
from django.db import models
from django.contrib import admin

class EntryAdmin(admin.ModelAdmin):
    form = EntryAdminForm
    formfield_overrides = {
        models.TextField: {'short_Text': RedactorEditor},
    }

```

**Comment by douglasmiranda** [comment]
That's the "quick-and-dirty" way (the docs said)
https://docs.djangoproject.com/pt-br/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides

I think that's a better way to do it: https://docs.djangoproject.com/pt-br/1.10/topics/forms/modelforms/#overriding-the-default-fields
