### ISSUE TITLE
Insertion images, invalid link.

### ISSUE THREAD

**Issue by NightStr** [douglasmiranda/django-wysiwyg-redactor#117]
When i inserted image, created wrong link, not enough slash in the beginning.

Example:

What is generated:
img src="static/uploads/Chrysanthemum.jpg"

What should be:
img src="/static/uploads/Chrysanthemum.jpg"

**Comment by panosl** [comment]
yeah, strange, I'm getting this too.

**Comment by panosl** [comment]
Heh, stupid issue. We hadn't defined MEDIA_URL and/or MEDIA_ROOT. Fixed it for me.

**Comment by douglasmiranda** [comment]
Yes, you must define the MEDIA_URL.
