### ISSUE TITLE
Redactor admin widget doesn't load in production environment with django's collectstatic

### ISSUE THREAD

**Issue by YeomansIII** [douglasmiranda/django-wysiwyg-redactor#119]
Redactor is working fine when running a local django server.  However, while using Nginx/Gunicorn/Django on my staging server I am getting the following error in the Chrome console.  I can't find the root of the issue and I am not sure why this would be occurring.  All files are being loaded properly and I am not getting any 404s.
`Uncaught TypeError: this.$editor.find(...).addBack is not a function`

My project is located here if you want to take a look at my configuration: https://github.com/YeomansIII/healthycookingfortoday/tree/master/django-project

**Comment by fission6** [comment]
a potential hint... i am having issues as well where i get Uncaught TypeError: document.getSelection is not a function in my production environment.

I think it has to do with the minification of redactor and jquery. the "unminimized" files (when debug = True) work fine.

Could be related to this as well.

**Comment by owise1** [comment]
I had this issue too and it turned out I was using an old jquery version. updating to 1.11 fixed it.

**Comment by douglasmiranda** [comment]
#137
