### ISSUE TITLE
Is anyone still maintaining the repo?

### ISSUE THREAD

**Issue by llann** [douglasmiranda/django-wysiwyg-redactor#122]
It's just to know if someone will continue to manage the Pull requests and the future of the repo?

**Comment by charlesthk** [comment]
I agree, is this repo still managed ?

**Comment by bravedick** [comment]
:skull:

**Comment by douglasmiranda** [comment]
I'll be back! 

(I'm trying, too much work to be done, but I believe this month I will be back :D)

**Comment by odero** [comment]
@douglasmiranda It would help if you at least accepted some pull requests or add someone to help you with this.

**Comment by gastlich** [comment]
@douglasmiranda ping

**Comment by douglasmiranda** [comment]
Guys, I've been away for a lot of reasons, work, health issues.. but now I think I can work again =]

Some of you could still help me? If you guys could test some Pull Requests and post here the ones I can merge without breaking stuff, would be nice.

I will be able to update the redactor to Redactor 2 :D, but let's close some PRs first xD

**Comment by nikolaik** [comment]
Suggest merging one of the Django 1.10 deprecation warning PR's (#114, #118, #125, #134, #135, #136).

Merge #134 which looks like the best one (no need to support outdated django versions anymore).

This also closes #120.

**Comment by rapilabs** [comment]
@douglasmiranda I'm sorry to hear about your issues but you could give someone permission to accept one of the PR's for the 1.10 removal of `patterns()`, then bump & release.

**Comment by gataga** [comment]
@douglasmiranda, I agree with @nikolaik: I have tested #134 and it does what it needs to. Please merge and release.

**Comment by douglasmiranda** [comment]
Thanks @mariocesar, @iquad, @wilima, @umgelurgel, @lomholdt for your contributions. To fix this I've merged #134 

Thanks to @nikolaik and @gataga for your help too =]

**Comment by douglasmiranda** [comment]
Please, check 0.4.9.1
