### ISSUE TITLE
Facebook embed

### ISSUE THREAD

**Issue by Alfredoero** [douglasmiranda/django-wysiwyg-redactor#123]
Hi i'm using this app for a blog that i have and when i try to upload an embed from facebook it doesn't look right, it renders the script tag as a text instead of a tag in consecuence the hole script appears in the content as a normal text. What can i do to fix this?

**Comment by douglasmiranda** [comment]
When you print the value of the variable with html content on the template you have to use the `safe` templatetag.

https://docs.djangoproject.com/pt-br/1.10/ref/templates/builtins/#safe

```
{{ article.html_text|safe }}
```

**Comment by douglasmiranda** [comment]
Closing for now, but feel free to reopen if you have more questions. =]
