### ISSUE TITLE
Static files?

### ISSUE THREAD

**Issue by sedrubal** [douglasmiranda/django-wysiwyg-redactor#129]
I did the instructions in readme but I can't manage to use it in a non admin site, because static files are missing. How can I include the static files in my template? `{{ form.media }}` didn't work...

**Comment by Jufik** [comment]
Have you tried
 `{% static  "redactor/static/redactor.js"%}` 
`{% static "redactor/css/redactor.css" %}` 
and which ever file you'll need?

**Comment by sedrubal** [comment]
Oh ok. Do you mean `{% static "redactor/redactor.js" %`?
But it didn't work neither. An somehow there is no `table.js` for example.

This static files are available after installing:

```
.env/lib/python2.7/site-packages/redactor/static/redactor
$ tree
.
├── css
│   ├── django_admin.css
│   ├── docstyle.css
│   ├── redactor.css
│   ├── redactor.less
│   ├── style.css
│   └── wym.css
├── img
│   └── icons.png
├── jquery.redactor.init.js
├── langs
│   ├── ar.js
│   ├── [...]
│   └── zh_tw.js
├── redactor.js
├── redactor.min.js
└── toolbars
    ├── default.js
    └── mini.js

4 directories, 59 files
```

**Comment by douglasmiranda** [comment]
#138
