### ISSUE TITLE
Plugins don't work

### ISSUE THREAD

**Issue by rootvar** [douglasmiranda/django-wysiwyg-redactor#130]
I installed latest versions of Table and Fullscreen plugins but they don't seem to be working. All references to 'this' in their code fail, e.g. 'this.core.editor is not a function', 'this.selection.current is not a function'. Logging this.lang.get('any-existing-string') directly from the table.js init function outputs a blank string.

This looks like a problem with the version of redactor in this repo.

**Comment by Jufik** [comment]
Got the same issue with the _video_ plugin found on the [official website](https://imperavi.com/redactor/plugins/video/).
Using this in the admin, an error `this.modal.getActionButton is not a function`.

**Comment by klimanek** [comment]
I confirm that. I downloaded the imagemanager.js (as it should support image browsing/choosing, see my latest thread) but it does not work. No other plugin seems to work either.

**Comment by Jufik** [comment]
It comes from redactor versions compatibility.
I found 10.0.2 compatible plugins in [this repo'](https://github.com/yiidoc/yii2-redactor/tree/master/assets/plugins). It works like a charm (at least in the admin).

**Comment by douglasmiranda** [comment]
Since I will upgrade the redactor version to Redactor 2, I will keep this open and let you guys know when everything will be ok.

**Comment by douglasmiranda** [comment]
You should try it: https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.0
