### ISSUE TITLE
Custom plugin displayed in all redactorfields.

### ISSUE THREAD

**Issue by lburdzy** [douglasmiranda/django-wysiwyg-redactor#144]
I added a custom plugin via `redactor_options = {'plugins': ['pluginname']}` argument in field definition. Even though I only added it to one field, the plugin shows up in all redactor fields. Even if they are in other models and other apps. I tried setting `redactor_options = {'plugins': []}` to other fields and setting it globaly, but to no effect. 

I'm using django 1.10 and django-wysiwyg-redactor 0.4.9.1. I think it worked fine in 0.4.9, but it does not seem to work with django 1.10. Any ideas what's causing the problem?

**Comment by lburdzy** [comment]
I have managed to fix my problem by removing the `REDACTOR_OPTIONS` setting. I had it set to 
```REDACTOR_OPTIONS = {'lang': 'en', 'plugins': []}```
but even having 
```REDACTOR_OPTIONS = {'lang': 'en'}``` or ```REDACTOR_OPTIONS = {}``` 
resulted in the bug occuring.

**Comment by douglasmiranda** [comment]
This probably fixed (d5105be69cc6df5e0667fcb0bbd3d80e3c454eb2), let me know if it persists.
