### ISSUE TITLE
handling CSS between editor and displaying content

### ISSUE THREAD

**Issue by tisdall** [douglasmiranda/django-wysiwyg-redactor#145]
Maybe I'm missing something simple, but there seems to be a large disconnect between how content is displayed in the editor and how it's displayed elsewhere.

For example, in the editor all the text is styled with `font-family: Menlo, Monaco, monospace, sans-serif !important;`.  If I save the form content and then insert that content on another page it's displayed using the styling surrounding it.

The only way I can see with handling this is creating my own CSS file that gets loaded after the `redactor.css` that tries to undo the styling in there to make the content in the editor look something like the content when displayed elsewhere.  Is this really how you have to handle this?

**Comment by tisdall** [comment]
BTW, I'm using this library on the front-end so I just need to use the surrounding formatting.

I'm wondering if perhaps I should inherit from `RedactorEditor` and then use my own copy of `redactor.css` with most of the `.redactor-editor` styling removed.

**Comment by douglasmiranda** [comment]
Yes, this is pretty much what you should do. If you want to show to the person editing on the Redactor, an accurate style of the final form of the content, I think your approach is valid.

Let me know if you made something different. =]
