### ISSUE TITLE
Undo button?

### ISSUE THREAD

**Issue by discopatrick** [douglasmiranda/django-wysiwyg-redactor#146]
I've been struggling to find the correct keywords for adding certain buttons to the toolbar - mostly because the documentation at the official redactor site is for Redactor II, and of course, due to licensing issues, this project only uses the old Redactor.

So, apologies if this is a very simple question, but can I add undo/redo buttons to django-wysiwyg-redactor?

Additionally, where can I find the documentation for the version of Redactor that is used in django-wysiwyg-redactor?

**Comment by douglasmiranda** [comment]
Now that we have Redactor II, you can follow the official docs xD https://imperavi.com/redactor/docs/how-to-add-button/
