### ISSUE TITLE
Add Python 3 support to PyPi

### ISSUE THREAD

**Issue by smaccona** [douglasmiranda/django-wysiwyg-redactor#147]
It appears Python 3 support was added in https://github.com/douglasmiranda/django-wysiwyg-redactor/pull/83. 

This should be documented in PyPi using a [trove classifier](https://pypi.python.org/pypi?%3Aaction=list_classifiers) by passing a [`classifier`](https://docs.python.org/3/distutils/setupscript.html#additional-meta-data)
argument to `setup()`), so that the package will be listed in the [Python 3 Packages list on PyPI](https://pypi.python.org/pypi?%3Aaction=packages_rss) and tools like https://github.com/brettcannon/caniusepython3 will work against this package.

I will make a PR for this.

**Comment by tisdall** [comment]
"PyPy" is something completely different from "PyPi".  You're talking about "PyPi".

**Comment by smaccona** [comment]
Oops - silly mistake on my part, of course! Corrected.
