### ISSUE TITLE
update redactor to 10.2.5

### ISSUE THREAD

**Issue by tisdall** [douglasmiranda/django-wysiwyg-redactor#149]
It seems like the version in this repo is 10.2.2 but the latest version before Redactor II was released was 10.2.5 .  Is it possible to update this repo to that version?

https://web.archive.org/web/20151009221116/http://imperavi.com/redactor/log/

**Comment by tisdall** [comment]
https://github.com/yiiext/imperavi-redactor-widget/tree/master/assets has 10.2.5 and several of the plugins.  It might be a good idea to include some of the plugins since they're difficult to find now.

**Comment by douglasmiranda** [comment]
By the end of the month I'll be working on this =]

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.0

Updated to Redactor II
