### ISSUE TITLE
Where to put downloaded plugins?

### ISSUE THREAD

**Issue by alzearafat** [douglasmiranda/django-wysiwyg-redactor#152]
Hi there!

Nice app, but I'm facing difficulty to find out where I should put the downloaed plugin? The Readme only mention to "Download the plugin", but nowhere about where I should put it.

I want to using codemirror plugin.

Any help would be greatly appreciated :)

Thank you

**Comment by alzearafat** [comment]
nevermind, find the answer :)

**Comment by jforaker** [comment]
this is github. share your answer :)

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-wysiwyg-redactor#using-plugins
