### ISSUE TITLE
Do not worry, I'll be back!

### ISSUE THREAD

**Issue by douglasmiranda** [douglasmiranda/django-wysiwyg-redactor#153]
Next things I will bring:

- update redactor and it's licensing
- fix issues
- plan new features
- refactor

So, the first thing will be updating the editor to the latest version. This will probably fix or invalidate some issues, and then we could move on.

**Comment by hmleal** [comment]
+1

**Comment by discopatrick** [comment]
@douglasmiranda can I help with this at all? We've got a project that might benefit from using the latest version, and we could use it very soon! :)

**Comment by douglasmiranda** [comment]
@discopatrick thanks for offering your help, I will ask your help, in the next few days xD

**Comment by discopatrick** [comment]
Still available to help, if needed.

**Comment by douglasmiranda** [comment]
Hey @discopatrick, please try the new version: 
https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.0

I'm going to start planning the changes I will make, rewrite what we have to, add missing features and more, so if you could give me a feedback about this release, it would be nice, so we can make this ok to proceed to new things. =]

**Comment by douglasmiranda** [comment]
Closing for now, please open issues, if you find bugs. =]
