### ISSUE TITLE
Upgrade to 2.4?

### ISSUE THREAD

**Issue by TylerFisher** [douglasmiranda/django-wysiwyg-redactor#157]
Hello,

I'm particularly bitten by a bug introduced in Redactor II that is fixed in version 2.4 (https://imperavi.com/redactor/log/). Can the repo upgrade the version or is there a way I can do so?

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.1
