### ISSUE TITLE
Uncaught ReferenceError: django is not defined 

### ISSUE THREAD

**Issue by speciose** [douglasmiranda/django-wysiwyg-redactor#52]
jQuery v2.1.1
Always have this error outside admin.

![untit1](https://cloud.githubusercontent.com/assets/8721324/4590710/35188804-5063-11e4-9b6f-b54f9a228a84.png)

Also. Redactor only working when jQuery.js in a Head of the html. When it's not I get this:

![untit2](https://cloud.githubusercontent.com/assets/8721324/4590860/de4e12a8-5064-11e4-9e80-dc4c693e9f48.png)

![untit3](https://cloud.githubusercontent.com/assets/8721324/4590861/e0b25fae-5064-11e4-8295-c497c2686fd5.png)

Other jQuery plugins works fine

**Comment by douglasmiranda** [comment]
#137
