### ISSUE TITLE
File upload doesnt work in IE

### ISSUE THREAD

**Issue by otined** [douglasmiranda/django-wysiwyg-redactor#60]
When I upload a document the link isn't attached (in all versions of IE). The file is placed in the correct folder and the document title is being added to the textfield, but there's no link.

**Comment by AAS** [comment]
Same on IE9 and django-wysiwyg-redactor 0.4.5.1

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.0
