### ISSUE TITLE
Not working in admin for older versions of Django

### ISSUE THREAD

**Issue by stevematney** [douglasmiranda/django-wysiwyg-redactor#64]
In trying to use Redactor in the admin for a project that's built in Django 1.5, redactor is throwing an undefined error (`this.$editor.on` is `undefined`) even if you're loading a newer version of jQuery to the page. This looks to be because [jquery.redactor.init.js](https://github.com/douglasmiranda/django-wysiwyg-redactor/blob/master/redactor/static/redactor/jquery.redactor.init.js#L2) is defining `jQuery` as `django.jQuery` which is on version 1.4 in Django 1.5. `.on()` wasn't added to jQuery until [1.7](http://api.jquery.com/on/).

**Comment by webknjaz** [comment]
Hi,
I worked around this by putting an empty `jquery.redactor.init.js` into my project. Hope this will help you.

P.S. @douglasmiranda please consider placing comment about this into README and/or this js file.

**Comment by douglasmiranda** [comment]
@webknjaz is right. I will create an issue to this.

**Comment by jonearley** [comment]
@webknjaz could you detail what you did to fix this? I'm in the same boat.

**Comment by webknjaz** [comment]
@jonearley just put `jquery.redactor.init.js` near your `plugins` folder in your project and then perform `collectstatic`, so it will replace file provided by this package.

**Comment by jonearley** [comment]
@webknjaz okay, I got an empty `jquery.redactor.init.js` loaded. Doesn't seem to help though, since I am still having issues.

Error: 'Uncaught TypeError: $(...).on is not a function'

<code>
$(window).on('load.tools.redactor', function() // Uncaught TypeError: $(...).on is not a function
	{
		$('[data-tools="redactor"]').redactor();
	});
</code>

**Comment by webknjaz** [comment]
@jonearley well, perhaps your issue isn't the same as mine.
What's your version of Django?
What version of jQuery is loaded? (may be checked via JS console)
Do you have some extra scripts loaded? Maybe they influence on jQuery behavior somehow.

**Comment by jonearley** [comment]
@webknjaz I am using Django version 1.5.4. Jquery version 1.4.2, the version the django admin loads in.  I wonder if I could tell redactor to use a different (newer) version of jquery?

**Comment by webknjaz** [comment]
In fact it uses newer version if you loaded it.

In this line redactor package tries to make use of django's default jquery:
https://github.com/douglasmiranda/django-wysiwyg-redactor/blob/master/redactor/static/redactor/jquery.redactor.init.js#L2

So if you overwrite it, it won't use django's jquery. But you still need to load it by youself. E.g. as follows:

```python
    class Media:
        js = (
            'https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js',
        )
```

**Comment by jonearley** [comment]
@webknjaz 
Thanks for detailing. I am struggling to figure out where to place the `class Media`. Where do you recommend?

And then would my `jquery.redactor.init.js` looks like this?

```javascript
if(typeof django !== "undefined") {
    jQuery = jQuery.noConflict(true);
}
```

**Comment by webknjaz** [comment]
@jonearley
1) I place it in `admin.py`.
2) No, it shouldn't look like this, besause in this case Redactor will use Django's version of jQuery, which is too old in 1.5
