### ISSUE TITLE
Height attribute getting added automatically when resizing images in the editor

### ISSUE THREAD

**Issue by jcalazan** [douglasmiranda/django-wysiwyg-redactor#68]
It looks like the newer versions are automatically adding the height attribute to the image, which doesn't work well if you want the images to be responsive.

Is there a setting to disable this? Tried looking at the redactor docs and couldn't find it.

**Comment by douglasmiranda** [comment]
You can do this in your CSS, by setting the height with !important.

On Redactor you only have the option to disable the resize: http://imperavi.com/redactor/docs/settings/images/#setting-imageResizable

**Comment by jcalazan** [comment]
Thanks Douglas!
