### ISSUE TITLE
changing toolbar style, adding plugins and showing more/less buttons?

### ISSUE THREAD

**Issue by deronsizemore** [douglasmiranda/django-wysiwyg-redactor#70]
I'm struggling to get this working on the front end but admin seems to be working great. So, I'm playing around with that for now.

I currently have this for my admin area:

    'summary': RedactorEditor(redactor_options={'plugins': ['video', 'fullscreen', 'counter', 'limiter'], 'limiter': '10000'}),

Can someone tell me how I would add the character counter and image manager plugins to the editor? Is it possible to do it in the above? The redactor docs for adding plugins are not really django-specific so it's not easy to follow for these two plugins.

How do I go about adding or removing buttons from the toolbar? I'd like to add view source and remove a few others that I don't need.

I'd also like to see what the default vs tiny toolbar style looks like but of course, don't know how to change that either.

Thanks

**Comment by webknjaz** [comment]
Hi,

It's stated in `README` that you should download those plugins and place them into corresponding directory.

Talking about removal, you may need to read `redactor.js` code (I did so), because some of buttons are implemented as a core functionality and it's impossible to disable them via official API.

**Comment by deronsizemore** [comment]
Sorry for the confusion. I probably didn't state my question clearly.

For the plugins, I've got them in the proper directory and have a couple of them working (like limiter and fullscreen). My problem is that for the character counter and image manager plugins. Once I've added them to the plugin directory, how then do I get them to show up on the editor in the admin?

I'm using this in my admin.py:

    'summary': RedactorEditor(redactor_options={'plugins': ['video', 'fullscreen', 'counter', 'limiter'], 'limiter': '10000'}),

The problem is that for character counter and image mangager, they both need some extra parameters to work, i.e., url for json for image manager and character limit, etc. for char counter. How do I add that stuff to the widgets line in the admin.py line above?

**Comment by webknjaz** [comment]
`imagemanager` plugin uses this global option `REDACTOR_UPLOAD`, which is mapped to handler class `REDACTOR_UPLOAD_HANDLER` ( https://github.com/douglasmiranda/django-wysiwyg-redactor#upload-handlers )
I don't know about `counter`, but it seems you may add callback (from http://imperavi.com/redactor/plugins/counter/ ) via `jquery.redactor.init.js` (w/ customization possibility introduced in #66).

**Comment by douglasmiranda** [comment]
Sorry for the delay, but i see @webknjaz already said all I would say.

I know we don't have much documentation, but all we can offer, for now, is in the README.

with something like:
```python
text = RedactorField(
    verbose_name="Text",
    redactor_options={
        'plugins': ['table'],
        'buttons': ['bold', 'italic', 'unorderedlist', 'orderedlist', 'outdent', 'file'],
    },
    allow_file_upload=True,
    allow_image_upload=True
)
```
You have custom buttons, plugin table on the toolbar and file upload.

When using image manager ( http://imperavi.com/redactor/plugins/image-manager/ ), you will have to create a view in your project, and set on redactor_options the option "imageManagerJson"

```python
{'imageManagerJson': reverse('MY_JSON_RESPONSE_VIEW')}
```

**Comment by deronsizemore** [comment]
thanks @webknjaz and @douglasmiranda. I think that makes sense.

So, just to clarify, for image manager, this line would be something like this?

    {'imageManagerJson': reverse('/redactor/image_manager')}

Where domain.com/redactor/image_manager would point to a view which returns a json response?

**Comment by douglasmiranda** [comment]
When using 'reverse', you will have, for example:

```python
url(
    r'^uploaded-files/$',
    view.RedactorUploadView.as_view(),
    name='redactor-uploaded-files-json'
),
```
```python
text = RedactorField(
    verbose_name="Text",
    redactor_options={
        # ...
        'imageManagerJson': reverse_lazy('redactor-uploaded-files-json')
    },
    allow_file_upload=True,
    allow_image_upload=True
)
```
So, as you can see, what you use as parameter in reverse/reverse_lazy is the url "name" parameter.

**Comment by deronsizemore** [comment]
Ok thanks! Makes sense I think. :)
