### ISSUE TITLE
Update Redactor.js to v10.0.7

### ISSUE THREAD

**Issue by webknjaz** [douglasmiranda/django-wysiwyg-redactor#71]
It is stated in `README` that this repo keeps `redactor.js` up-to-date. But the latest version was issued on Jan 7, 2015.
I think, it's time to make an upgrade.

P.S. Changelog:
- `NEW` Option `clear` for `formattingAdd` to make it replace styles and classes rather then merge them
- `IMPROVED` Tables pasted from `MS Word` into Headers were not cleaned up perfectly
- `IMPROVED` Various placeholder improvements
- `IMPROVED` Table headers are now marked up with proper `<th>` tag
- `IMPROVED` Better `Brazilian Portuguese` and `Norwegian` translations
- `IMPROVED` Empty Redactor now returns truly empty data upon submission
- `IMPROVED` 'body-hidden' of Redactor dropdowns has been renamed to 'body-redactor-hidden' for better compatibility with various frameworks
- `IMPROVED` .opacity variable in redactor.less has been renamed to opacity-redactor for better compatibility with Bootstrap
- `FIXED` `imageEditable: false` turns off image resizing as well
- `FIXED` Pasted text in `Internet Explorer` gets an extra space
- `FIXED` Video Plugin ignores iframe width parameter
- `FIXED` Uploaded files do not get links in `Internet Explorer 10`
- `FIXED` Links with '~' and/or '+' were truncated improperly upon conversion by 'convertUrlLinks'
- `FIXED` 'Pre'-wrapped HTML code of a webpage being rendered improperly
- `FIXED` Small images with links display link tooltip on click
- `FIXED` Empty lines being deleted in `Internet Explorer 10-11` even with 'removeEmpty: false' setting
- `FIXED` In Firefox in 'linebreaks' mode all text typed after pasting something being deleted upon pressing Return key
- `FIXED` 'rel' attribute being removed from all links
- `FIXED` Malfunctioning links editing feature in all versions of Internet Explorer
- `FIXED` In `Internet Explorer 10` and `Firefox` users were unable to leave tables when table is the last item in Redactor
- `FIXED` Unexpected `div` instead of `p` sometimes when leaving a paragraph
- `FIXED` `Shift+Enter` only works successfully on the second attempt when in non-linebreaks mode
- `FIXED` Switching from source code mode to visual mode sometimes applied selection to the surrounding page
- `FIXED` Video being deleted with the last character of the text in `Redactor`
- `FIXED` Various focus issues in `iOS 8`
- `FIXED` `tabKey: false` malfunctioning when there's text in Redactor
- `FIXED` Pasted text resulted in an extra empty `<span>` and loses `<p>` upon adding an image
- `FIXED` applying B/I after a word could sometimes make `Redactor` lose focus

**Comment by webknjaz** [comment]
UPD: 10.0.7 already released.

**Comment by douglasmiranda** [comment]
426c6e753a417bf3292ba47f370407a8cd46a596
