### ISSUE TITLE
Works on django-admin but I have problem to get it works on my views

### ISSUE THREAD

**Issue by karimone** [douglasmiranda/django-wysiwyg-redactor#72]
I have many problems to get refactor working on my views.

First error: jQuery not defined. I had to load the jQuery from the end of the body to the head
than I got this
Second Error: ReferenceError: redactor_default_options is not defined

Should be the default options set as default? Anyway if works in django-admin that means that I'm doing something wrong. Any idea?

**Comment by karimone** [comment]
I figure out the problem. (after a couple of hours)

I had to:

* link the refactor static folder in my static
* add {{ form.media }} at the bottom of the template

now works, but I offer my self to add these details on the wiki page.

**Comment by masterrex** [comment]
Thanks for the tip, karimone.

**Comment by karimone** [comment]
yw :-)

**Comment by jonearley** [comment]
@karimone @masterrex Trying to use `RedactorField` in my admin. I added a newer version of JQuery so it works with my Django version 1.5.4, but I am getting the `Uncaught ReferenceError: redactor_default_options is not defined` error. I am not sure what to do. Any thoughts?

Here is the line that throws the error:

```javascript
<textarea cols="40" id="id_content" name="content" rows="10">
with some content</textarea><script>jQuery(document).ready(function(){jQuery("#id_content").redactor(jQuery.extend({}, redactor_default_options, {"lang": "en", "fileUpload": "/redactor/upload/file/", "plugins": ["video", "bufferbuttons", "fullscreen"], "buttons": ["formatting", "bold", "italic", "link", "unorderedlist", "orderedlist", "image", "file", "video", "horizontalrule", "html"], "formatting": ["p", "h3", "blockquote"], "imageUpload": "/redactor/upload/image/"}));});</script>
```

**Comment by karimone** [comment]
based on the error, I think you didn't define a setting in base.py

**Comment by jonearley** [comment]
I thought so too, but I have settings defined. 

```python
#settings.py
REDACTOR_OPTIONS = {
    'lang': 'en',
    'buttons': ['formatting', 'bold', 'italic', 'link',
'unorderedlist', 'orderedlist',
'image', 'file', 'video', 'horizontalrule', 'html', ],
    'plugins': ['video', 'bufferbuttons', 'fullscreen'],
    'formatting': ['p', 'h3', 'blockquote',],
}
REDACTOR_UPLOAD = 'uploads/'
```

**Comment by karimone** [comment]
Copy and paste all the error


-- 
Karim Norman Gorjux

**Comment by jonearley** [comment]
@karimone the problem has seemed to fix itself and I am not sure why. Oh well, it works. Thanks for helping.

**Comment by karimone** [comment]
Good. Check the compatibility with your django version.
