### ISSUE TITLE
edit as html not possible anymore

### ISSUE THREAD

**Issue by Visgean** [douglasmiranda/django-wysiwyg-redactor#73]
Since updating to the latest version I am unable to edit the inner html... The button seems to be lost.

**Comment by kotyy** [comment]
I can confirm the presence of this. It occurs even when setting `REDACTOR_OPTIONS['buttons'] = ['html',]`.

**Comment by kotyy** [comment]
After a bit more digging, it looks like this was a change [made in Redactor itself](http://forum.grabaperch.com/forum/10-27-2014-new-redactor-is-missing-html-button), not related to this project.

However, you can solve the issue by adding `REDACTOR_OPTIONS['buttonSource'] = True`.

**Comment by Visgean** [comment]
Thanks
