### ISSUE TITLE
Upload requires user to be staff member

### ISSUE THREAD

**Issue by fpytloun** [douglasmiranda/django-wysiwyg-redactor#78]
To upload files/images, user has to be staff member. It is not always desired behavior (sometimes it should be ok if user is authenticated or has some role) and unfortunately it can't be configured.
Also staff_member_required decorator forces login_url to admin which is not desired for some projects.

https://github.com/douglasmiranda/django-wysiwyg-redactor/blob/master/redactor/views.py#L23

**Comment by douglasmiranda** [comment]
Yes, I agree we need to do this better, probably a way to enable and disable.

**Comment by fpytloun** [comment]
What about following simple solution:
```
upload_auth_decorator = getattr(settings, 'REDACTOR_AUTH_DECORATOR', staff_member_required)
...
@method_decorator(upload_auth_decorator)
```

Usage example (untested):
```
## Decorator for authentication
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import user_passes_test

def editor_role_required(redirect_field_name=REDIRECT_FIELD_NAME, perm='application.is_editor', login_url='user:login'):
    """
    Decorator for views that checks that the user is logged and has permissions
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_active and u.has_perm(perm),
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )

    return actual_decorator

## Redactor settings
REDACTOR_AUTH_DECORATOR=editor_role_required
```

Or do you have some better idea how to solve this?

**Comment by fpytloun** [comment]
Here's the solution: https://github.com/douglasmiranda/django-wysiwyg-redactor/pull/82
Tested with login_required decorator and working fine.

**Comment by douglasmiranda** [comment]
Merged!
