### ISSUE TITLE
django utils

### ISSUE THREAD

**Issue by ram0973** [douglasmiranda/django-wysiwyg-redactor#81]
C:\Python27\lib\site-packages\redactor\utils.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

C:\Python27\lib\site-packages\redactor\utils.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

**Comment by douglasmiranda** [comment]
Fixed #81
