### ISSUE TITLE
Label not visible when named content

### ISSUE THREAD

**Issue by ocZio** [douglasmiranda/django-wysiwyg-redactor#84]
Hi all,

I had a quick look for this issue and it seems that when we have the following (notice the naming of content)

```python
content = RedactorField()
```

In django's administration the LABEL element just disappears, the culprit seems to be 

```css
.field-content label { display: none; }
```
in django_admin.css.

Is there a reason we have field-content specifically removing the visibility of the LABEL element? 

Thanks.

**Comment by kawa-marcin** [comment]
Same issue I had. Can confirm

**Comment by douglasmiranda** [comment]
Django version? I'm testing on Django 1.8 and the visibility its ok.

**Comment by ocZio** [comment]
Hello Douglas,

Did you name the field

```python
content 
```

?

**Comment by douglasmiranda** [comment]
o.O Now I understand. Ok, I will fix.
