### ISSUE TITLE
Resize image on upload

### ISSUE THREAD

**Issue by banzayats** [douglasmiranda/django-wysiwyg-redactor#88]
Is it possible to add option that allows to customize (reduce) the size of uploaded photos?

**Comment by douglasmiranda** [comment]
Hmm, I think you will be able to do it by creating a custom upload handler https://github.com/douglasmiranda/django-wysiwyg-redactor#upload-handlers

**Comment by agusmakmun** [comment]
Hello there, how i can resize/autoscale the image uploaded?
for example, i uploaded image and then in the redactor editor should be:

```html
<a href="/media/path/to/origin.png">
  <img src="/media/path/to/scale.png">
</a>
```

> I'm not use `HTML` source in my editor.
