### ISSUE TITLE
Image editing problem

### ISSUE THREAD

**Issue by Voxmundi** [douglasmiranda/django-wysiwyg-redactor#91]
When clicked on uploaded image to edit, its continue resizing even if mouse button released.

**Comment by douglasmiranda** [comment]
This is probably a redactor issue, I will check it out anyway.

**Comment by Voxmundi** [comment]
When its debugged on Chrome, its giving: Uncaught RangeError: Maximum call stack size exceeded   jquery-1.8.3.min.js:2

**Comment by douglasmiranda** [comment]
Hey @Voxmundi since I didn't have this problem so far, could you please try the updated version? 

https://pypi.python.org/pypi/django-wysiwyg-redactor/0.4.9

It has a lot of fixes, maybe the redactor team solved your problem =]

**Comment by pythdasch** [comment]
Hi, I'm facing the same problem with the last version. I've the 0.4.9 and the problem is the same as vocmundsi. How can I fix it ?

**Comment by javipalanca** [comment]
Hi, I have the same error.
django-wysiwyg-redactor==0.4.9
django-suit-redactor==0.0.4
django-suit==0.2.21
Django==1.9.8

Javascript console error:
`Uncaught RangeError: Maximum call stack size exceeded jquery-1.8.3.min.js:2`

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-wysiwyg-redactor/releases/tag/0.5.0
