### ISSUE TITLE
Uncaught ReferenceError: RedactorPlugins is not defined

### ISSUE THREAD

**Issue by mishbahr** [douglasmiranda/django-wysiwyg-redactor#94]
Firstly, thank you for this awesome package. 

I wanted to use the `fullscreen` from here:

http://imperavi.com/redactor/plugins/fullscreen/

So as instructed in the Readme, I downloaded it and placed in my `static` directory:

    static/redactor/plugins/fullscreen.js

And I'm only using the `RedactorEditor` widget in my admin:

    from django import forms
    from redactor.widgets import RedactorEditor
    from blog.models import Category

    class CategoryForm(forms.ModelForm):

        class Meta:
            model = Category
            widgets = {
                'description': RedactorEditor(
                    allow_file_upload=False,
                    allow_image_upload=False,
                    redactor_options={'plugins': ['fullscreen']}
                ),
        }

However, when I go back to my `Category` change form in django admin, the fullscreen plugin is not enabled and I'm getting the following error in the chrome developer console:

    Uncaught ReferenceError: RedactorPlugins is not defined 
    redactor.js:1430

Please advise me what I should to to get this working. Thank you again!

django==1.7.9
django-wysiwyg-redactor==0.4.8.1

**Comment by Steefkroon** [comment]
Im leaving a comment here, cause I'm having the same problem.

**Comment by allisson** [comment]
Same error here. Django 1.7, video plugin don't work.

django-wysiwyg-redactor==0.4.8.1

**Comment by yaniv14** [comment]
Same issue with Django 1.8.3
The editor works but with no plugins.

**Comment by douglasmiranda** [comment]
Hmm you all are using this outside the django admin right?

I'm gonna check this out.

**Comment by yaniv14** [comment]
I can only speak for myself :)
Thanks.

**Comment by mishbahr** [comment]
Nope. I'm using it in django admin

**Comment by Steefkroon** [comment]
I'm using redactor outside admin. The rest works great though, its just the plugins that seem to be giving this error.

**Comment by Steefkroon** [comment]
Any updates on this problem?

**Comment by czubik8805** [comment]
Same issue with Django 1.6.11

```
Uncaught ReferenceError: RedactorPlugins is not defined
```
editor works without any plugins.

**Comment by sdnall** [comment]
I was running into this issue as well - I don't see anywhere in the bundled redactor.js where RedactorPlugins is ever initialized.

Updating the bundled redactor.js with a more recent version seems to allow me to load plugins again. I don't think I am allowed to paste the updated source, but here's the version info for redactor.js that I used.

        Redactor 10.2.2
	Updated: July 15, 2015

	http://imperavi.com/redactor/

	Copyright (c) 2009-2015, Imperavi LLC.
	License: http://imperavi.com/redactor/license/

**Comment by douglasmiranda** [comment]
Great, I will look into it this weekend.

**Comment by rentgeeen** [comment]
Yes I saw that one, I read it before I have created this one, I have no error showing up, it is working but buttons are missing

**Comment by luzfcb** [comment]
@douglasmiranda you will have some time to upgrade to 10.2.2? I suppose this can be done quickly

**Comment by the0rem** [comment]
If you want to get your plugins running immediately, you can update their code to be compatible with this version of redactor.

For each plugin you need to update the Object that the plugin is adding the method to. So for example, replace the following:

```
(function($)
{
	$.Redactor.prototype.fontcolor = function()
```

with:

```
if (!RedactorPlugins) var RedactorPlugins = {};

(function($)
{
	RedactorPlugins.fontcolor = function()
```

You can do this with all of their plugins and they will work as expected.

**Comment by rentgeeen** [comment]
the0rem
Hm strange, did not work

**Comment by rentgeeen** [comment]
the0rem 
Nice, it worked!
Thank you

**Comment by douglasmiranda** [comment]
Sorry the delay, this next week I will finally have some time to work on this.

**Comment by douglasmiranda** [comment]
Fixed https://pypi.python.org/pypi/django-wysiwyg-redactor/0.4.9

Thanks a lot for your feedback guys, appreciate it. :D

Any issues, reopen, please.

**Comment by deronsizemore** [comment]
I'm attempting to get this working as well and I've got the button added, but it doesn't function correctly. Here's what I see when I hover over the fullscreen button: http://i.imgur.com/0g7Yaea.png. Clicking the button does nothing.

I'm using version 0.4.9 of django-wysiwyg-redactor. 

Here's my code for this in my admin area:

```
'body': RedactorEditor(
	redactor_options={
	'formatting': ['p', 'blockquote', 'h2', 'h3'],
	'buttons': ['formatting', 'bold', 'italic', 'deleted', 'lists', 'link', 'unorderedlist', 'orderedlist', 'alignment', 'image', 'html',],
	'plugins': ['fullscreen',],
	},
),
```

I've viewed source on the admin page and the fullscreen.js is included in the source and accessible, so I know it's seeing it.

What am I missing here?

**Comment by deronsizemore** [comment]
For what it's worth, I just checked and am getting: `Uncaught TypeError: this.core.box is not a function` in console. Looks like the same sort of issue as this: https://github.com/pydanny/django-wysiwyg/issues/55 (different django app). I'm just not sure what to update in the fullscreen.js code to fix it.

**Comment by deronsizemore** [comment]
Sorry for all the comments, but I think I got it. Looks like in the redactor.js code that `core.box` is now `core.getBox`.

Once I fixed that error, it blew up on `core.editor` which needed to be updated to `core.getEditor` inside fullscreen.js. So, it's going fullscreen now width-wise. It's not going fullscreen height-wise which I think I can fix in the CSS. 

When you hover over the button, it isn't showing the "aria-label" which in this case should read: `FULLSCREEN`. Is there a way to force that somehow in the admin.py redactorEditor() declaration?

**Comment by deronsizemore** [comment]
Turns out that fixing the aria-label on fullscreen can be done inside of redactor.js in this section:

```
langs: {
			en: {
				html: 'HTML',
				video: 'Insert Video',
				image: 'Insert Image',
				table: 'Table',
				link: 'Link',
				link_insert: 'Insert link',
				link_edit: 'Edit link',
				unlink: 'Unlink',
				formatting: 'Formatting',
				paragraph: 'Normal text',
				quote: 'Quote',
				code: 'Code',
				header1: 'Header 1',
				header2: 'Header 2',
				header3: 'Header 3',
				header4: 'Header 4',
				header5: 'Header 5',
				bold: 'Bold',
				italic: 'Italic',
				fontcolor: 'Font Color',
				backcolor: 'Back Color',
				unorderedlist: 'Unordered List',
				orderedlist: 'Ordered List',
				outdent: 'Outdent',
				indent: 'Indent',
				cancel: 'Cancel',
				insert: 'Insert',
				save: 'Save',
				_delete: 'Delete',
				insert_table: 'Insert Table',
				insert_row_above: 'Add Row Above',
				insert_row_below: 'Add Row Below',
				insert_column_left: 'Add Column Left',
				insert_column_right: 'Add Column Right',
				delete_column: 'Delete Column',
				delete_row: 'Delete Row',
				delete_table: 'Delete Table',
				rows: 'Rows',
				columns: 'Columns',
				add_head: 'Add Head',
				delete_head: 'Delete Head',
				title: 'Title',
				image_position: 'Position',
				none: 'None',
				left: 'Left',
				right: 'Right',
				center: 'Center',
				image_web_link: 'Image Web Link',
				text: 'Text',
				mailto: 'Email',
				web: 'URL',
				video_html_code: 'Video Embed Code or Youtube/Vimeo Link',
				file: 'Insert File',
				upload: 'Upload',
				download: 'Download',
				choose: 'Choose',
				or_choose: 'Or choose',
				drop_file_here: 'Drop file here',
				align_left: 'Align text to the left',
				align_center: 'Center text',
				align_right: 'Align text to the right',
				align_justify: 'Justify text',
				horizontalrule: 'Insert Horizontal Rule',
				deleted: 'Deleted',
				anchor: 'Anchor',
				link_new_tab: 'Open link in new tab',
				underline: 'Underline',
				alignment: 'Alignment',
				filename: 'Name (optional)',
				edit: 'Edit',
				upload_label: 'Drop file here or ',
				fullscreen: 'Fullscreen'
			}
		},
```

Just add: `fullscreen: 'Fullscreen'`

**Comment by CARocha** [comment]
@deronsizemore i have the same error
but i use Redactor 10.2.2
when load the plugins fullscreen and click the button this appears
fullscreen.js:45 Uncaught TypeError: this.core.editor is not a function(…)

i find in redactor.js the core.getBox but now not exist :(
any idea, it the same error for all plugins like table,counter,fullscreen,video etc, i think
the plugin version in older but any idea for upgrade or update de code??
i read the solution @deronsizemore but disapear the core.getBox and getEditor() too 

thank
