### ISSUE TITLE
Video, Fullscreen or anything is not showing up

### ISSUE THREAD

**Issue by rentgeeen** [douglasmiranda/django-wysiwyg-redactor#95]
I created by manual a project, but as hard I am trying any buttons like Video, Fullscreen are not showing up. The Editor works but any new buttons I cannot make to work in Django Admin.

settings.py 

    REDACTOR_OPTIONS = {'lang': 'en', 'focus':'true'}
    REDACTOR_UPLOAD = 'uploads/'

models.py

    from redactor.fields import RedactorField

    teaser = RedactorField(redactor_options={'plugins': ['video']})
    home_teaser = RedactorField(redactor_options={'plugins': ['video']})
    description = RedactorField(redactor_options={'plugins': ['video']})

admin.py

    from redactor.widgets import RedactorEditor

    class NewsAdminForm(forms.ModelForm):
    class Meta:
        model = News
        widgets = {
           'description': RedactorEditor(),
           'home_teaser': RedactorEditor(),
           'teaser': RedactorEditor(),
        }

     class NewsAdmin(admin.ModelAdmin):
     # ...
     list_display = ('title',)
     prepopulated_fields = {'title_url': ('title',),}
     form = NewsAdminForm

     admin.site.register(News, NewsAdmin)

I tried every possible combination also puttin this into model:

    description = RedactorField(
        # for example, if you downloaded the 'video' plugin:
        redactor_options={'plugins': ['video']}
    )

and no luck. Django version 1.7.7

![pcgcjq4gqq-h-8pnnoarl6qctsev9vllspaf-jojfvo](https://cloud.githubusercontent.com/assets/770676/8891362/49ca6ac8-32f4-11e5-8e02-9632f3189379.png)

**Comment by mishbahr** [comment]
Checkout issue #94 — I think its the same issue.

**Comment by rentgeeen** [comment]
Yes I saw that one, I read it before I have created this one, I have no error showing up, it is working but buttons are missing
